import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/prisma/prisma.service';
import { Prisma } from '@prisma/client';

@Injectable()
export class PdfReportService {
  constructor(private readonly prisma: PrismaService) {}

  private formatCurrency(amount: string | number | Prisma.Decimal, currency = 'PKR'): string {
    const num = typeof amount === 'string' ? parseFloat(amount) : typeof amount === 'number' ? amount : parseFloat(amount.toString());
    return `${currency} ${num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  }

  private getHtmlHeader(title: string, orgName: string, subtitle?: string): string {
    return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a1a; padding: 40px; font-size: 12px; }
  .header { text-align: center; margin-bottom: 30px; border-bottom: 3px solid #1a1a1a; padding-bottom: 15px; }
  .header h1 { font-size: 22px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; }
  .header h2 { font-size: 16px; font-weight: 600; color: #444; margin-top: 4px; }
  .header .subtitle { font-size: 11px; color: #666; margin-top: 4px; }
  .meta { display: flex; justify-content: space-between; margin-bottom: 20px; }
  .meta-item { font-size: 11px; }
  .meta-item strong { display: block; font-size: 10px; text-transform: uppercase; color: #666; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  th { background: #f5f5f5; border: 1px solid #ddd; padding: 8px 10px; text-align: left; font-size: 11px; text-transform: uppercase; font-weight: 600; }
  td { border: 1px solid #ddd; padding: 7px 10px; font-size: 11px; }
  tr:nth-child(even) { background: #fafafa; }
  .amount { text-align: right; font-variant-numeric: tabular-nums; }
  .total-row { font-weight: 700; background: #f0f0f0 !important; }
  .group-row { font-weight: 600; background: #e8e8e8 !important; }
  .footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 10px; color: #888; text-align: center; }
  .signature-area { display: flex; justify-content: space-between; margin-top: 60px; }
  .signature-line { width: 200px; border-top: 1px solid #333; padding-top: 5px; font-size: 10px; text-align: center; }
  @media print { body { padding: 20px; } .no-print { display: none; } }
</style></head><body>
<div class="header">
  <h1>${orgName}</h1>
  <h2>${title}</h2>
  ${subtitle ? `<div class="subtitle">${subtitle}</div>` : ''}
</div>`;
  }

  private getHtmlFooter(orgName: string): string {
    return `<div class="footer">
  <p>Generated by Grainix ERP | ${orgName} | ${new Date().toISOString().split('T')[0]}</p>
  <p>Powered by Asad Ali 0308-4420406</p>
</div></body></html>`;
  }

  // ===== SALES INVOICE PDF =====

  async generateInvoiceHtml(organizationId: string, invoiceId: string) {
    const invoice = await this.prisma.salesInvoice.findFirst({
      where: { id: invoiceId, organizationId },
      include: {
        customer: true,
        journalEntry: { include: { lines: { include: { account: true } } } },
      },
    });
    if (!invoice) throw new NotFoundException('Invoice not found');

    const org = await this.prisma.organization.findUnique({ where: { id: organizationId } });
    const currency = org?.currency || 'PKR';

    let html = this.getHtmlHeader('Sales Invoice', org?.name || 'Organization', `Invoice #${invoice.invoiceNumber}`);

    html += `<div class="meta">
      <div class="meta-item"><strong>Invoice No</strong>${invoice.invoiceNumber}</div>
      <div class="meta-item"><strong>Date</strong>${new Date(invoice.date).toISOString().split('T')[0]}</div>
      <div class="meta-item"><strong>Due Date</strong>${invoice.dueDate ? new Date(invoice.dueDate).toISOString().split('T')[0] : 'N/A'}</div>
      <div class="meta-item"><strong>Payment Status</strong>${invoice.paymentStatus}</div>
    </div>`;

    html += `<div style="margin-bottom: 20px;">
      <strong>Bill To:</strong><br>
      ${invoice.customer?.name || 'N/A'}<br>
      ${invoice.customer?.phone ? `Phone: ${invoice.customer.phone}<br>` : ''}
      ${invoice.customer?.address || ''}
    </div>`;

    html += `<table><thead><tr>
      <th>Description</th><th class="amount">Amount</th>
    </tr></thead><tbody>`;

    html += `<tr><td>Subtotal</td><td class="amount">${this.formatCurrency(invoice.totalAmount, currency)}</td></tr>`;
    html += `<tr><td>Tax</td><td class="amount">${this.formatCurrency(invoice.taxAmount, currency)}</td></tr>`;
    html += `<tr><td>Discount</td><td class="amount">${this.formatCurrency(invoice.discount, currency)}</td></tr>`;
    html += `<tr class="total-row"><td><strong>Net Amount</strong></td><td class="amount"><strong>${this.formatCurrency(invoice.netAmount, currency)}</strong></td></tr>`;

    html += `</tbody></table>`;

    if (invoice.journalEntry) {
      html += `<h3 style="margin: 20px 0 10px;">Journal Entry: ${invoice.journalEntry.entryNumber}</h3>`;
      html += `<table><thead><tr><th>Account</th><th class="amount">Debit</th><th class="amount">Credit</th></tr></thead><tbody>`;
      for (const line of invoice.journalEntry.lines) {
        html += `<tr><td>${line.account.code} - ${line.account.name}</td>
          <td class="amount">${parseFloat(line.debit.toString()) > 0 ? this.formatCurrency(line.debit, currency) : '-'}</td>
          <td class="amount">${parseFloat(line.credit.toString()) > 0 ? this.formatCurrency(line.credit, currency) : '-'}</td></tr>`;
      }
      html += `</tbody></table>`;
    }

    html += `<div class="signature-area">
      <div class="signature-line">Prepared By</div>
      <div class="signature-line">Received By</div>
      <div class="signature-line">Authorized Signature</div>
    </div>`;

    html += this.getHtmlFooter(org?.name || '');
    return { html, invoiceNumber: invoice.invoiceNumber };
  }

  // ===== TRIAL BALANCE PDF =====

  async generateTrialBalanceHtml(organizationId: string, fiscalYearId?: string) {
    const org = await this.prisma.organization.findUnique({ where: { id: organizationId } });
    const currency = org?.currency || 'PKR';

    const accounts = await this.prisma.chartOfAccount.findMany({
      where: { organizationId, isGroup: false, isActive: true },
      orderBy: { code: 'asc' },
    });

    let html = this.getHtmlHeader('Trial Balance', org?.name || '', `As of ${new Date().toISOString().split('T')[0]}`);

    html += `<table><thead><tr>
      <th>Code</th><th>Account Name</th><th>Type</th><th class="amount">Debit</th><th class="amount">Credit</th>
    </tr></thead><tbody>`;

    let totalDebit = new Prisma.Decimal(0);
    let totalCredit = new Prisma.Decimal(0);

    for (const account of accounts) {
      const result = await this.prisma.journalEntryLine.aggregate({
        where: {
          accountId: account.id,
          journalEntry: { organizationId, isPosted: true, deletedAt: null, ...(fiscalYearId ? { fiscalYearId } : {}) },
        },
        _sum: { debit: true, credit: true },
      });

      const debit = new Prisma.Decimal(result._sum.debit?.toString() || '0');
      const credit = new Prisma.Decimal(result._sum.credit?.toString() || '0');
      const opening = new Prisma.Decimal(account.openingBalance.toString());

      let balanceDebit = new Prisma.Decimal(0);
      let balanceCredit = new Prisma.Decimal(0);

      if (account.balanceType === 'DEBIT') {
        const net = opening.add(debit).sub(credit);
        if (net.greaterThanOrEqualTo(0)) balanceDebit = net;
        else balanceCredit = net.abs();
      } else {
        const net = opening.add(credit).sub(debit);
        if (net.greaterThanOrEqualTo(0)) balanceCredit = net;
        else balanceDebit = net.abs();
      }

      if (balanceDebit.equals(0) && balanceCredit.equals(0)) continue;

      totalDebit = totalDebit.add(balanceDebit);
      totalCredit = totalCredit.add(balanceCredit);

      html += `<tr>
        <td>${account.code}</td><td>${account.name}</td><td>${account.accountType}</td>
        <td class="amount">${balanceDebit.greaterThan(0) ? this.formatCurrency(balanceDebit, currency) : '-'}</td>
        <td class="amount">${balanceCredit.greaterThan(0) ? this.formatCurrency(balanceCredit, currency) : '-'}</td>
      </tr>`;
    }

    html += `<tr class="total-row"><td colspan="3"><strong>Total</strong></td>
      <td class="amount"><strong>${this.formatCurrency(totalDebit, currency)}</strong></td>
      <td class="amount"><strong>${this.formatCurrency(totalCredit, currency)}</strong></td></tr>`;

    const diff = totalDebit.sub(totalCredit);
    if (!diff.equals(0)) {
      html += `<tr style="color: red;"><td colspan="3"><strong>DIFFERENCE</strong></td>
        <td class="amount" colspan="2"><strong>${this.formatCurrency(diff, currency)}</strong></td></tr>`;
    }

    html += `</tbody></table>`;
    html += this.getHtmlFooter(org?.name || '');
    return { html, isBalanced: diff.equals(0) };
  }

  // ===== P&L PDF =====

  async generateProfitLossHtml(organizationId: string, fromDate?: string, toDate?: string) {
    const org = await this.prisma.organization.findUnique({ where: { id: organizationId } });
    const currency = org?.currency || 'PKR';

    const dateFilter: Prisma.JournalEntryWhereInput = {};
    if (fromDate) dateFilter.date = { gte: new Date(fromDate) };
    if (toDate) dateFilter.date = { ...(dateFilter.date as Record<string, Date> || {}), lte: new Date(toDate) };

    const period = fromDate && toDate
      ? `${fromDate} to ${toDate}`
      : `As of ${new Date().toISOString().split('T')[0]}`;

    let html = this.getHtmlHeader('Profit & Loss Statement', org?.name || '', period);

    const revenueAccounts = await this.prisma.chartOfAccount.findMany({
      where: { organizationId, accountType: 'REVENUE', isGroup: false },
      orderBy: { code: 'asc' },
    });

    const expenseAccounts = await this.prisma.chartOfAccount.findMany({
      where: { organizationId, accountType: 'EXPENSE', isGroup: false },
      orderBy: { code: 'asc' },
    });

    let totalRevenue = new Prisma.Decimal(0);
    let totalExpense = new Prisma.Decimal(0);

    html += `<table><thead><tr><th colspan="2">Revenue</th><th class="amount">Amount</th></tr></thead><tbody>`;
    for (const acc of revenueAccounts) {
      const result = await this.prisma.journalEntryLine.aggregate({
        where: { accountId: acc.id, journalEntry: { organizationId, isPosted: true, deletedAt: null, ...dateFilter } },
        _sum: { debit: true, credit: true },
      });
      const net = new Prisma.Decimal(result._sum.credit?.toString() || '0').sub(new Prisma.Decimal(result._sum.debit?.toString() || '0'));
      if (net.equals(0)) continue;
      totalRevenue = totalRevenue.add(net);
      html += `<tr><td>${acc.code}</td><td>${acc.name}</td><td class="amount">${this.formatCurrency(net, currency)}</td></tr>`;
    }
    html += `<tr class="total-row"><td colspan="2"><strong>Total Revenue</strong></td><td class="amount"><strong>${this.formatCurrency(totalRevenue, currency)}</strong></td></tr></tbody></table>`;

    html += `<table><thead><tr><th colspan="2">Expenses</th><th class="amount">Amount</th></tr></thead><tbody>`;
    for (const acc of expenseAccounts) {
      const result = await this.prisma.journalEntryLine.aggregate({
        where: { accountId: acc.id, journalEntry: { organizationId, isPosted: true, deletedAt: null, ...dateFilter } },
        _sum: { debit: true, credit: true },
      });
      const net = new Prisma.Decimal(result._sum.debit?.toString() || '0').sub(new Prisma.Decimal(result._sum.credit?.toString() || '0'));
      if (net.equals(0)) continue;
      totalExpense = totalExpense.add(net);
      html += `<tr><td>${acc.code}</td><td>${acc.name}</td><td class="amount">${this.formatCurrency(net, currency)}</td></tr>`;
    }
    html += `<tr class="total-row"><td colspan="2"><strong>Total Expenses</strong></td><td class="amount"><strong>${this.formatCurrency(totalExpense, currency)}</strong></td></tr></tbody></table>`;

    const netIncome = totalRevenue.sub(totalExpense);
    html += `<table><tr class="total-row" style="font-size: 14px;">
      <td><strong>Net ${netIncome.greaterThanOrEqualTo(0) ? 'Profit' : 'Loss'}</strong></td>
      <td class="amount" style="color: ${netIncome.greaterThanOrEqualTo(0) ? '#16a34a' : '#dc2626'}">
        <strong>${this.formatCurrency(netIncome.abs(), currency)}</strong></td></tr></table>`;

    html += this.getHtmlFooter(org?.name || '');
    return { html, totalRevenue: totalRevenue.toString(), totalExpense: totalExpense.toString(), netIncome: netIncome.toString() };
  }

  // ===== BALANCE SHEET PDF =====

  async generateBalanceSheetHtml(organizationId: string, asOfDate?: string) {
    const org = await this.prisma.organization.findUnique({ where: { id: organizationId } });
    const currency = org?.currency || 'PKR';
    const date = asOfDate || new Date().toISOString().split('T')[0];

    let html = this.getHtmlHeader('Balance Sheet', org?.name || '', `As of ${date}`);

    const sections: { type: string; label: string }[] = [
      { type: 'ASSET', label: 'Assets' },
      { type: 'LIABILITY', label: 'Liabilities' },
      { type: 'EQUITY', label: 'Equity' },
    ];

    const totals: Record<string, Prisma.Decimal> = {};

    for (const section of sections) {
      const accounts = await this.prisma.chartOfAccount.findMany({
        where: { organizationId, accountType: section.type as Prisma.EnumAccountTypeFilter, isGroup: false },
        orderBy: { code: 'asc' },
      });

      let sectionTotal = new Prisma.Decimal(0);
      html += `<table><thead><tr><th colspan="2">${section.label}</th><th class="amount">Amount</th></tr></thead><tbody>`;

      for (const acc of accounts) {
        const result = await this.prisma.journalEntryLine.aggregate({
          where: {
            accountId: acc.id,
            journalEntry: { organizationId, isPosted: true, deletedAt: null, date: { lte: new Date(date) } },
          },
          _sum: { debit: true, credit: true },
        });

        const debit = new Prisma.Decimal(result._sum.debit?.toString() || '0');
        const credit = new Prisma.Decimal(result._sum.credit?.toString() || '0');
        const opening = new Prisma.Decimal(acc.openingBalance.toString());

        const balance = acc.balanceType === 'DEBIT'
          ? opening.add(debit).sub(credit)
          : opening.add(credit).sub(debit);

        if (balance.equals(0)) continue;
        sectionTotal = sectionTotal.add(balance);

        html += `<tr><td>${acc.code}</td><td>${acc.name}</td><td class="amount">${this.formatCurrency(balance, currency)}</td></tr>`;
      }

      html += `<tr class="total-row"><td colspan="2"><strong>Total ${section.label}</strong></td><td class="amount"><strong>${this.formatCurrency(sectionTotal, currency)}</strong></td></tr></tbody></table>`;
      totals[section.type] = sectionTotal;
    }

    const liabAndEquity = (totals['LIABILITY'] || new Prisma.Decimal(0)).add(totals['EQUITY'] || new Prisma.Decimal(0));
    const assets = totals['ASSET'] || new Prisma.Decimal(0);

    html += `<table style="margin-top: 20px;">
      <tr class="total-row"><td><strong>Total Assets</strong></td><td class="amount"><strong>${this.formatCurrency(assets, currency)}</strong></td></tr>
      <tr class="total-row"><td><strong>Total Liabilities + Equity</strong></td><td class="amount"><strong>${this.formatCurrency(liabAndEquity, currency)}</strong></td></tr>
    </table>`;

    html += this.getHtmlFooter(org?.name || '');
    return { html, isBalanced: assets.equals(liabAndEquity), totalAssets: assets.toString() };
  }

  // ===== DELIVERY CHALLAN PDF =====

  async generateDeliveryChallanHtml(organizationId: string, challanId: string) {
    const challan = await this.prisma.deliveryChallan.findFirst({
      where: { id: challanId, organizationId },
      include: { customer: true, vehicle: true },
    });
    if (!challan) throw new NotFoundException('Delivery challan not found');

    const org = await this.prisma.organization.findUnique({ where: { id: organizationId } });

    let html = this.getHtmlHeader('Delivery Challan', org?.name || '', `Challan #${challan.challanNumber}`);

    html += `<div class="meta">
      <div class="meta-item"><strong>Challan No</strong>${challan.challanNumber}</div>
      <div class="meta-item"><strong>Date</strong>${new Date(challan.date).toISOString().split('T')[0]}</div>
      <div class="meta-item"><strong>Vehicle</strong>${challan.vehicle?.vehicleNumber || 'N/A'}</div>
      <div class="meta-item"><strong>Status</strong>${challan.status}</div>
    </div>`;

    html += `<div style="margin-bottom: 20px;">
      <strong>Deliver To:</strong> ${challan.customer?.name || 'N/A'}<br>
      <strong>Driver:</strong> ${challan.driverName || 'N/A'} ${challan.driverPhone ? `(${challan.driverPhone})` : ''}
    </div>`;

    if (challan.notes) {
      html += `<div style="margin-bottom: 20px;"><strong>Notes:</strong> ${challan.notes}</div>`;
    }

    html += `<div class="signature-area">
      <div class="signature-line">Dispatched By</div>
      <div class="signature-line">Driver Signature</div>
      <div class="signature-line">Received By</div>
    </div>`;

    html += this.getHtmlFooter(org?.name || '');
    return { html, challanNumber: challan.challanNumber };
  }

  // ===== PURCHASE ORDER PDF =====

  async generatePurchaseOrderHtml(organizationId: string, poId: string) {
    const po = await this.prisma.purchaseOrder.findFirst({
      where: { id: poId, organizationId },
      include: { supplier: true, items: true },
    });
    if (!po) throw new NotFoundException('Purchase order not found');

    const org = await this.prisma.organization.findUnique({ where: { id: organizationId } });
    const currency = org?.currency || 'PKR';

    let html = this.getHtmlHeader('Purchase Order', org?.name || '', `PO #${po.orderNumber}`);

    html += `<div class="meta">
      <div class="meta-item"><strong>PO Number</strong>${po.orderNumber}</div>
      <div class="meta-item"><strong>Date</strong>${new Date(po.date).toISOString().split('T')[0]}</div>
      <div class="meta-item"><strong>Expected Date</strong>${po.expectedDate ? new Date(po.expectedDate).toISOString().split('T')[0] : 'N/A'}</div>
      <div class="meta-item"><strong>Status</strong>${po.status}</div>
    </div>`;

    html += `<div style="margin-bottom: 20px;">
      <strong>Supplier:</strong> ${po.supplier?.name || 'N/A'}<br>
      ${po.supplier?.phone ? `Phone: ${po.supplier.phone}<br>` : ''}
    </div>`;

    html += `<table><thead><tr>
      <th>#</th><th>Description</th><th>Qty</th><th>Unit</th><th class="amount">Rate</th><th class="amount">Amount</th>
    </tr></thead><tbody>`;

    po.items.forEach((item, i) => {
      html += `<tr><td>${i + 1}</td><td>Item</td><td>${item.quantity}</td><td>${item.unit || 'KG'}</td>
        <td class="amount">${this.formatCurrency(item.rate, currency)}</td><td class="amount">${this.formatCurrency(item.amount, currency)}</td></tr>`;
    });

    html += `<tr class="total-row"><td colspan="5"><strong>Total</strong></td>
      <td class="amount"><strong>${this.formatCurrency(po.totalAmount, currency)}</strong></td></tr></tbody></table>`;

    if (po.narration) {
      html += `<div style="margin-top: 20px;"><strong>Notes:</strong> ${po.narration}</div>`;
    }

    html += `<div class="signature-area">
      <div class="signature-line">Prepared By</div>
      <div class="signature-line">Approved By</div>
      <div class="signature-line">Authorized Signature</div>
    </div>`;

    html += this.getHtmlFooter(org?.name || '');
    return { html, orderNumber: po.orderNumber };
  }

  // ===== GENERAL LEDGER PDF =====

  async generateGeneralLedgerHtml(organizationId: string, accountId: string, fromDate?: string, toDate?: string) {
    const account = await this.prisma.chartOfAccount.findFirst({
      where: { id: accountId, organizationId },
    });
    if (!account) throw new NotFoundException('Account not found');

    const org = await this.prisma.organization.findUnique({ where: { id: organizationId } });
    const currency = org?.currency || 'PKR';

    const dateWhere: Prisma.JournalEntryWhereInput = {};
    if (fromDate) dateWhere.date = { gte: new Date(fromDate) };
    if (toDate) dateWhere.date = { ...(dateWhere.date as Record<string, Date> || {}), lte: new Date(toDate) };

    let html = this.getHtmlHeader(`General Ledger - ${account.code} ${account.name}`, org?.name || '',
      fromDate && toDate ? `${fromDate} to ${toDate}` : 'All Periods');

    const lines = await this.prisma.journalEntryLine.findMany({
      where: {
        accountId,
        journalEntry: { organizationId, isPosted: true, deletedAt: null, ...dateWhere },
      },
      include: { journalEntry: true },
      orderBy: { journalEntry: { date: 'asc' } },
    });

    let runningBalance = new Prisma.Decimal(account.openingBalance.toString());

    html += `<table><thead><tr>
      <th>Date</th><th>Entry #</th><th>Narration</th><th class="amount">Debit</th><th class="amount">Credit</th><th class="amount">Balance</th>
    </tr></thead><tbody>`;

    html += `<tr class="group-row"><td colspan="5"><strong>Opening Balance</strong></td>
      <td class="amount"><strong>${this.formatCurrency(runningBalance, currency)}</strong></td></tr>`;

    for (const line of lines) {
      const d = new Prisma.Decimal(line.debit.toString());
      const c = new Prisma.Decimal(line.credit.toString());
      if (account.balanceType === 'DEBIT') {
        runningBalance = runningBalance.add(d).sub(c);
      } else {
        runningBalance = runningBalance.add(c).sub(d);
      }

      html += `<tr>
        <td>${new Date(line.journalEntry.date).toISOString().split('T')[0]}</td>
        <td>${line.journalEntry.entryNumber}</td>
        <td>${line.narration || line.journalEntry.narration || '-'}</td>
        <td class="amount">${d.greaterThan(0) ? this.formatCurrency(d, currency) : '-'}</td>
        <td class="amount">${c.greaterThan(0) ? this.formatCurrency(c, currency) : '-'}</td>
        <td class="amount">${this.formatCurrency(runningBalance, currency)}</td>
      </tr>`;
    }

    html += `<tr class="total-row"><td colspan="5"><strong>Closing Balance</strong></td>
      <td class="amount"><strong>${this.formatCurrency(runningBalance, currency)}</strong></td></tr>`;

    html += `</tbody></table>`;
    html += this.getHtmlFooter(org?.name || '');
    return { html, closingBalance: runningBalance.toString() };
  }
}
